# Generated by Django 3.1.2 on 2020-11-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzeriaSignupResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('street_address1', models.CharField(blank=True, max_length=100, verbose_name='Street Address 1')),
                ('street_address2', models.CharField(blank=True, max_length=100, verbose_name='Street Address 2')),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('vegan_pizza_type', models.CharField(max_length=200)),
                ('menu_description', models.TextField(blank=True)),
                ('facebook_page', models.CharField(blank=True, max_length=200)),
                ('online_ordering_link', models.CharField(blank=True, max_length=200)),
                ('pizza_photo', models.ImageField(blank=True, upload_to='images/')),
                ('is_subscriber', models.BooleanField(default=False, help_text='Indicates whether this pizzeria subscribes to PMQ Magazine', verbose_name='Subscribes to PMQ?')),
                ('is_approved', models.BooleanField(default=False, help_text='Indicates whether this listing has been approved for display')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('pizza_description', models.TextField(blank=True)),
            ],
        ),
    ]
