# Generated by Django 3.2.3 on 2021-07-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_pizzeriasignupresponse_surveyresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PizzeriaSignupResponse',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
