# Generated by Django 3.2.3 on 2021-06-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeriaprofile',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pizzeriaprofile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pizzeriaprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pizzeriaprofile',
            name='online_ordering',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pizzeriaprofile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
