# Generated by Django 3.2.3 on 2021-06-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210602_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
        migrations.RenameModel(
            old_name='PizzeriaLocations',
            new_name='PizzeriaLocation',
        ),
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
