# Generated by Django 3.2.3 on 2021-06-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210602_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzeriaprofile',
            old_name='linkedin',
            new_name='tiktok',
        ),
        migrations.AddField(
            model_name='pizzeriaprofile',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
