# Generated by Django 3.2.3 on 2021-06-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210605_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzerialocation',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pizzerialocation',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pizzerialocation',
            name='street_address1',
            field=models.CharField(max_length=100, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='pizzerialocation',
            name='zip_code',
            field=models.CharField(max_length=15),
        ),
    ]
