# Generated by Django 3.2.3 on 2021-08-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210622_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzerialocation',
            name='location_website',
            field=models.URLField(blank=True),
        ),
    ]
