# Generated by Django 3.2.3 on 2021-06-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default='', max_length=100, verbose_name='Company/Pizzeria Name'),
            preserve_default=False,
        ),
    ]
