# Generated by Django 3.2.3 on 2021-06-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='online_ordering',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pizzeria_logo',
            field=models.ImageField(blank=True, upload_to='images/pizzeria_logos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
