# Generated by Django 3.2.3 on 2021-08-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210605_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pizzeria_website',
            field=models.URLField(blank=True),
        ),
    ]
