# Generated by Django 3.1.2 on 2020-12-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsinglepage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
